# Generated by Django 4.2.8 on 2024-02-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_food_historysale_reviewfood_remove_itemimage_item_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reviewfood",
        ),
    ]
