# Generated by Django 4.2.8 on 2024-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_delete_reviewfood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="category",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="order",
            name="material",
            field=models.CharField(max_length=50),
        ),
    ]
